version: '3.3'
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: 'root'
      POSTGRES_PASSWORD: 'root'
      POSTGRES_DB: 'ch'
    ports:
      - '5432:5432'
    # данные всех бд контейнера будут сохранены в /home/user/postgres-data
    volumes:
      - ./database-init:/docker-entrypoint-initdb.d



  adminer:
    image: adminer
    restart: always
    ports:
      - 8090:8080