spring:
  application:
    name: character-creator
    version: 0.0.1-SNAPSHOT
    description: Приложение для управления игровыми персонажами и гильдиями; выполнения игровых логик


  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      generate-ddl: true
      hibernate:
        show_sql: false
        format_sql: false
    show-sql: false
  datasource:
#    url: jdbc:postgresql://localhost:5432/ch
    url: jdbc:p6spy:postgresql://localhost:5432/ch
    username: root
    password: root
#    driverClassName: org.postgresql.Driver
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver

server:
  port: 8080
  servlet:
    context-path: /character-creator


springdoc:
  contact:
    name: Никита Ковалев
    email: qweezique@gmail.com